import type { Lang } from "./types.ts";

const copy = {
  "app.name": ["JANMARG", "JANMARG"],
  "app.tagline": ["Five schemes. One path.", "पाँच योजनाएँ। एक रास्ता।"],
  "app.hero": [
    "See why your scholarship file is stuck, and how to fix it.",
    "जानें आपकी छात्रवृत्ति फ़ाइल क्यों अटकी है, और उसे कैसे ठीक करें।",
  ],
  "auth.title": ["Sign in", "साइन इन"],
  "auth.create": ["Create account", "खाता बनाएँ"],
  "auth.have": ["Already have an account? Sign in", "खाता है? साइन इन करें"],
  "auth.need": ["New here? Create an account", "नए हैं? खाता बनाएँ"],
  "auth.email": ["Email", "ईमेल"],
  "auth.password": ["Password", "पासवर्ड"],
  "auth.password2": ["Confirm password", "पासवर्ड फिर लिखें"],
  "auth.submitIn": ["Sign in", "साइन इन"],
  "auth.guest": ["Continue as guest", "अतिथि के रूप में जारी रखें"],
  "auth.guestNote": ["", ""],
  "guest.title": ["Choose a student", "एक छात्र चुनें"],
  "guest.body": ["Open the file you want to work on.", "जिस फ़ाइल पर काम करना है, उसे खोलें।"],
  "guest.asha": ["Class 11. Income certificate is out of date.", "कक्षा 11। आय प्रमाण पत्र पुराना है।"],
  "guest.birsa": ["Undergraduate. The file can be reviewed and sent.", "स्नातक। फ़ाइल देखकर भेजी जा सकती है।"],
  "guest.meera": ["Overseas plan. Offer letter is still missing.", "विदेश योजना। प्रस्ताव पत्र अभी नहीं है।"],
  "guest.dev": ["Class 12. Marksheet name does not match.", "कक्षा 12। अंकपत्र का नाम नहीं मिलता।"],
  "guest.nila": ["Class 12. A draft is saved on this browser.", "कक्षा 12। मसौदा इसी ब्राउज़र पर है।"],
  "dock.caption": ["Looks at this file, then the cited extract.", "पहले यह फ़ाइल देखता है, फिर उद्धृत अंश।"],
  "dock.close": ["Close", "बंद करें"],
  "dock.empty": ["Ask about a stuck check, a document, or a scheme rule.", "अटकी जाँच, दस्तावेज़, या योजना नियम के बारे में पूछें।"],
  "dock.withName": ["{name}, ask about this file.", "{name}, इस फ़ाइल के बारे में पूछें।"],
  "dock.q1": ["Why is this file stuck?", "यह फ़ाइल क्यों अटकी है?"],
  "dock.q2": ["Which document should I fix first?", "पहले कौन सा दस्तावेज़ ठीक करूँ?"],
  "dock.q3": ["Can I send an application now?", "क्या मैं अभी आवेदन भेज सकता हूँ?"],
  "jago.thinking": ["JAGO is reading the extract…", "JAGO अंश पढ़ रहा है…"],
  "jago.speak": ["Read aloud", "सुनें"],
  "jago.speakFail": ["Voice playback is not available right now.", "अभी आवाज़ नहीं चल सकी।"],
  "jago.listening": ["Listening…", "सुन रहा है…"],
  "jago.voiceNo": ["This browser has no speech input.", "इस ब्राउज़र में आवाज़ इनपुट नहीं है।"],
  "portal.title": ["Public portals", "सार्वजनिक पोर्टल"],
  "portal.body": ["Checked as public pages. No student session is open on any of them.", "सार्वजनिक पन्नों के रूप में जाँचा गया। किसी पर छात्र सत्र खुला नहीं है।"],
  "portal.refused": ["Connection refused", "कनेक्शन मना"],
  "portal.nsp": ["National Scholarship Portal", "नेशनल स्कॉलरशिप पोर्टल"],
  "portal.sfmp": ["Canara SFMP", "केनरा एसएफएमपी"],
  "portal.nos": ["National Overseas Scholarship", "राष्ट्रीय विदेशी छात्रवृत्ति"],
  "portal.locker": ["DigiLocker", "डिजिलॉकर"],
  "auth.submitUp": ["Create account", "खाता बनाएँ"],
  "auth.hint": ["Use a real email and a password of at least 8 characters. No Aadhaar number.", "असली ईमेल और कम से कम 8 अक्षर का पासवर्ड लिखें। आधार नंबर नहीं।"],
  "auth.mismatch": ["The two passwords do not match.", "दोनों पासवर्ड एक जैसे नहीं हैं।"],
  "auth.short": ["Password must be at least 8 characters.", "पासवर्ड कम से कम 8 अक्षर का होना चाहिए।"],
  "auth.badEmail": ["Enter a valid email address.", "सही ईमेल लिखें।"],
  "setup.title": ["Your scholarship file", "आपकी छात्रवृत्ति फ़ाइल"],
  "setup.body": ["This stays on your account. It is not sent to a live government portal.", "यह आपके खाते में रहता है। इसे किसी लाइव सरकारी पोर्टल पर नहीं भेजा जाता।"],
  "setup.save": ["Save and open my desk", "सहेजें और डेस्क खोलें"],
  "setup.consent": ["I agree JANMARG may store this profile to check scheme rules.", "मैं सहमत हूँ कि JANMARG नियम जाँच के लिए यह प्रोफ़ाइल रखे।"],
  "setup.need": ["Fill every field and accept the consent line.", "हर जगह भरें और सहमति चुनें।"],
  "field.goal": ["Goal", "लक्ष्य"],
  "goal.domestic": ["Study in India", "भारत में पढ़ाई"],
  "goal.overseas": ["Study abroad", "विदेश में पढ़ाई"],
  "goal.research": ["Research", "शोध"],
  "more.account": ["Account", "खाता"],
  "more.alerts": ["Deficiency alerts", "कमी की सूचना"],
  "more.statusAlerts": ["Status alerts", "स्थिति की सूचना"],
  "more.signedOut": ["Signed out", "साइन आउट हो गया"],
  "docs.add": ["Add a document record", "दस्तावेज़ रिकॉर्ड जोड़ें"],
  "docs.added": ["Document saved to your wallet.", "दस्तावेज़ वॉलेट में सहेजा गया।"],
  "docs.refShort": ["Reference (masked)", "संदर्भ (छुपा हुआ)"],
  "prof.edit": ["Edit profile", "प्रोफ़ाइल बदलें"],
  "prof.saved": ["Profile saved to your account.", "प्रोफ़ाइल आपके खाते में सहेजी गई।"],
  "demo.banner": [
    "JANMARG",
    "जानमार्ग",
  ],
  "demo.long": [
    "DigiLocker, academic records, identity, and scheme portals here are records on this desk. No Aadhaar, bank account, or real student file is used. A match is not a sanction and not a payment.",
    "यहाँ DigiLocker, शैक्षणिक रिकॉर्ड, पहचान और पोर्टल सभी हैं। आधार, बैंक खाता या असली छात्र फ़ाइल नहीं है। मेल का मतलब संस्वीकृति या भुगतान नहीं है।",
  ],
  "common.loading": ["Loading your desk", "आपकी डेस्क खुल रही है"],
  "common.errorTitle": ["This screen did not load", "यह स्क्रीन नहीं खुली"],
  "common.errorBody": [
    "A source did not respond. Nothing was rejected. Try again.",
    "एक स्रोत ने जवाब नहीं दिया। कुछ अस्वीकार नहीं हुआ। फिर कोशिश करें।",
  ],
  "common.offlineTitle": ["You are offline", "आप ऑफ़लाइन हैं"],
  "common.offlineBody": [
    "Saved items on this phone are still here. Sending a file needs a connection.",
    "इस फ़ोन पर सहेजी चीज़ें यहीं हैं। फ़ाइल भेजने के लिए कनेक्शन चाहिए।",
  ],
  "common.deniedTitle": ["You cannot open this", "आप यह नहीं खोल सकते"],
  "common.deniedBody": [
    "This view is not allowed for the current role.",
    "मौजूदा भूमिका के लिए यह दृश्य अनुमति में नहीं है।",
  ],
  "common.emptyTitle": ["Nothing here yet", "अभी यहाँ कुछ नहीं है"],
  "common.retry": ["Try again", "फिर कोशिश करें"],
  "common.back": ["Back", "वापस"],
  "common.continue": ["Continue", "आगे बढ़ें"],
  "common.close": ["Close", "बंद करें"],
  "common.next": ["Next", "अगला"],
  "common.save": ["Save on this phone", "इस फ़ोन पर सहेजें"],
  "common.saved": ["Saved on this phone.", "इस फ़ोन पर सहेज लिया।"],
  "common.mock": ["Record", "रिकॉर्ड"],
  "common.step": ["Step {step} of {total}", "चरण {step} / {total}"],
  "lang.en": ["English", "English"],
  "lang.hi": ["हिन्दी", "हिन्दी"],
  "lang.pick": ["Choose a language", "भाषा चुनें"],
  "nav.menu": ["Main menu", "मुख्य मेनू"],
  "nav.home": ["Home", "होम"],
  "nav.documents": ["Documents", "दस्तावेज़"],
  "nav.jago": ["Ask", "पूछें"],
  "nav.alerts": ["Alerts", "सूचना"],
  "nav.more": ["More", "और"],
  "skip": ["Skip to content", "सामग्री पर जाएँ"],
  "on.personaTitle": ["Choose a student", "एक छात्र चुनें"],
  "on.personaBody": [
    "Pick a student file to see what is blocked and how to clear it.",
    "एक छात्र फ़ाइल चुनें और देखें क्या अटका है और उसे कैसे हटाएँ।",
  ],
  "on.otpTitle": ["Enter the verification code", "सत्यापन कोड डालें"],
  "on.otpBody": [
    "This is not an SMS from a government system. The code is shown here so you can try a wrong code and the right one.",
    "यह किसी सरकारी सिस्टम का एसएमएस नहीं है। कोड यहाँ दिखाया गया है ताकि गलत और सही दोनों आज़मा सकें।",
  ],
  "on.otpLabel": ["6-digit verification code", "6 अंकों का सत्यापन कोड"],
  "on.otpFill": ["Fill verification code", "सत्यापन कोड भरें"],
  "on.otpBad": ["That code does not match. Use the verification code shown above.", "यह कोड मेल नहीं खाता। ऊपर दिया सत्यापन कोड इस्तेमाल करें।"],
  "on.consentTitle": ["Before we open the desk", "डेस्क खोलने से पहले"],
  "on.consent1": [
    "We use only the few fields needed to explain a match: name, study stage, institute, income, and documents.",
    "मेल समझाने के लिए केवल कुछ फ़ील्ड हैं: नाम, पढ़ाई, संस्थान, आय और दस्तावेज़।",
  ],
  "on.consent2": [
    "Connectors run on this desk. You can revoke the document locker copy later.",
    "कनेक्टर हैं। दस्तावेज़ लॉकर प्रति बाद में वापस ले सकते हैं।",
  ],
  "on.consent3": [
    "JAGO answers only from the desk’s checked extracts and shows the source. It does not decide eligibility.",
    "JAGO केवल डेस्क के अनुमोदित अंशों से जवाब देता है और स्रोत दिखाता है। यह पात्रता तय नहीं करता।",
  ],
  "on.accept": ["I understand. Continue.", "मैं समझता/समझती हूँ। आगे बढ़ें।"],
  "on.decline": ["Do not continue", "आगे न बढ़ें"],
  "on.declinedTitle": ["Consent is required", "सहमति ज़रूरी है"],
  "on.declinedBody": [
    "Without consent the desk stays closed. No file was sent anywhere.",
    "सहमति के बिना डेस्क बंद रहेगी। कोई फ़ाइल कहीं नहीं भेजी गई।",
  ],
  "on.backConsent": ["Read consent again", "सहमति फिर पढ़ें"],
  "persona.asha": ["Class 11. Income certificate is out of date.", "कक्षा 11। आय प्रमाण पत्र पुराना है।"],
  "persona.birsa": ["Undergraduate at a notified institute in the sample.", "नमूने के अधिसूचित संस्थान में स्नातक।"],
  "persona.meera": ["Overseas study. Offer letter is not on file.", "विदेशी पढ़ाई। प्रस्ताव पत्र फ़ाइल में नहीं है।"],
  "persona.dev": ["Marksheet name and profile name differ.", "अंकपत्र का नाम और प्रोफ़ाइल का नाम अलग है।"],
  "persona.nila": ["A draft is saved on this phone.", "एक मसौदा इस फ़ोन पर सहेजा है।"],
  "home.progress": ["{done} of {total} checks are clear", "{total} में से {done} जाँच पूरी हैं"],
  "home.schemes": ["All five schemes", "सभी पाँच योजनाएँ"],
  "home.alerts": ["Alerts", "सूचनाएँ"],
  "home.seeAll": ["See all", "सभी देखें"],
  "home.journey": ["Latest on the file", "फ़ाइल पर ताज़ा स्थिति"],
  "home.noJourney": ["No application has been sent yet.", "अभी कोई आवेदन नहीं भेजा गया।"],
  "home.openJourney": ["Open the timeline", "समयरेखा खोलें"],
  "home.next": ["Next step", "अगला कदम"],
  "home.openItems": ["Open items", "खुली बातें"],
  "home.openNone": ["No open item on this scheme.", "इस योजना पर कोई खुली बात नहीं है।"],
  "home.notRejection": ["A source that does not respond is not a rejection. The file stays here.", "स्रोत का जवाब न आना अस्वीकृति नहीं है। फ़ाइल यहीं रहती है।"],
  "home.clearTitle": ["Nothing is blocking this scheme", "इस योजना पर कोई रोक नहीं है"],
  "home.clearBody": [
    "Current current rules do not show a hard stop. This is still not a sanction.",
    "मौजूदा मौजूदा नियमों में कोई सख्त रोक नहीं है। फिर भी यह संस्वीकृति नहीं है।",
  ],
  "card.renewIncome.title": ["Income certificate is out of date", "आय प्रमाण पत्र पुराना है"],
  "card.renewIncome.body": [
    "Post-Matric needs a current income certificate. An expired one stops the file before any decision. This is not a rejection.",
    "पोस्ट-मैट्रिक के लिए चालू आय प्रमाण पत्र चाहिए। पुराना पत्र फैसले से पहले फ़ाइल रोक देता है। यह अस्वीकृति नहीं है।",
  ],
  "card.renewIncome.cta": ["Fix this", "इसे ठीक करें"],
  "card.fixName.title": ["The name does not match", "नाम मेल नहीं खाता"],
  "card.fixName.body": [
    "The marksheet says {right}. Your profile says {left}. Verification pauses until they match or a person reviews the case.",
    "अंकपत्र पर {right} है। प्रोफ़ाइल पर {left} है। जब तक मेल न हो या कोई व्यक्ति समीक्षा न करे, सत्यापन रुका रहेगा।",
  ],
  "card.fixName.cta": ["Resolve the name", "नाम सुलझाएँ"],
  "card.addOffer.title": ["Overseas offer is not on file", "विदेशी प्रस्ताव फ़ाइल में नहीं है"],
  "card.addOffer.body": [
    "Readiness stays incomplete without admission evidence. This is not a rejection and not a selection.",
    "दाखिले के प्रमाण के बिना तैयारी अधूरी है। यह अस्वीकृति नहीं और चयन नहीं है।",
  ],
  "card.addOffer.cta": ["See the checklist", "जाँच-सूची देखें"],
  "card.addPassport.title": ["Passport evidence is missing", "पासपोर्ट प्रमाण नहीं है"],
  "card.addPassport.body": [
    "Overseas readiness asks for passport evidence as well as an offer. Missing proof is not a decision.",
    "विदेशी तैयारी में प्रस्ताव के साथ पासपोर्ट प्रमाण भी चाहिए। कमी कोई फैसला नहीं है।",
  ],
  "card.addPassport.cta": ["See the checklist", "जाँच-सूची देखें"],
  "card.openWizard.title": ["You can prepare a application", "आप आवेदन तैयार कर सकते हैं"],
  "card.openWizard.body": [
    "The current rules match so far. Submitting creates a receipt only. It does not sanction funds.",
    "मौजूदा नियम अभी तक मेल खाते हैं। भेजने पर केवल रसीद बनेगी। धन संस्वीकृत नहीं होगा।",
  ],
  "card.openWizard.cta": ["Continue application", "आवेदन जारी रखें"],
  "card.resumeDraft.title": ["A draft is waiting on this phone", "एक मसौदा इस फ़ोन पर इंतज़ार कर रहा है"],
  "card.resumeDraft.body": [
    "It was saved on this device, including while offline. Review it, then send the application when you are online.",
    "यह इस डिवाइस पर सहेजा गया था, ऑफ़लाइन भी। जाँचें, और ऑनलाइन होने पर आवेदन भेजें।",
  ],
  "card.resumeDraft.cta": ["Resume draft", "मसौदा जारी रखें"],
  "card.seeWhy.title": ["This scheme does not match", "यह योजना मेल नहीं खाती"],
  "card.seeWhy.body": [
    "One or more current rules do not fit. Open the result to see which line failed and why.",
    "एक या अधिक मौजूदा नियम नहीं बैठते। परिणाम खोलें और देखें कौन सी पंक्ति क्यों फिसली।",
  ],
  "card.seeWhy.cta": ["See why", "कारण देखें"],
  "card.retry.title": ["The check could not be finished", "जाँच पूरी नहीं हो सकी"],
  "card.retry.body": [
    "A connector did not respond. Eligibility could not be checked. This is not a rejection.",
    "एक कनेक्टर ने जवाब नहीं दिया। पात्रता जाँची नहीं जा सकी। यह अस्वीकृति नहीं है।",
  ],
  "card.retry.cta": ["Try the check again", "जाँच फिर करें"],
  "card.readiness.title": ["Readiness is still open", "तैयारी अभी खुली है"],
  "card.readiness.body": [
    "Some overseas evidence is still missing. A complete list is not a promise of an award.",
    "कुछ विदेशी प्रमाण अभी बाकी हैं। पूरी सूची पुरस्कार का वादा नहीं है।",
  ],
  "card.readiness.cta": ["Open readiness", "तैयारी खोलें"],
  "card.infoOnly.title": ["This scheme is information only", "यह योजना केवल जानकारी के लिए है"],
  "card.infoOnly.body": [
    "You can read the rules and your match. This desk does not submit an application for it.",
    "नियम और अपना मेल पढ़ सकते हैं। यह इसके लिए आवेदन जमा नहीं करता।",
  ],
  "card.infoOnly.cta": ["Read the scheme", "योजना पढ़ें"],
  "card.viewJourney.title": ["A file is in motion", "एक फ़ाइल चल रही है"],
  "card.viewJourney.body": [
    "Open the timeline to see the current owner and the latest event. The does not invent a sanction.",
    "समयरेखा खोलें और देखें अभी मालिक कौन है और आखिरी घटना क्या है। संस्वीकृति नहीं गढ़ता।",
  ],
  "card.viewJourney.cta": ["Open timeline", "समयरेखा खोलें"],
  "card.manualReview.title": ["A person needs to review the name", "नाम की समीक्षा किसी व्यक्ति को करनी है"],
  "card.manualReview.body": [
    "The spelling difference cannot be cleaned up automatically. Manual review was requested. No decision is made here.",
    "वर्तनी का अंतर अपने आप नहीं सुधरता। मैनुअल समीक्षा माँगी गई है। यहाँ कोई फैसला नहीं होता।",
  ],
  "card.manualReview.cta": ["See the review", "समीक्षा देखें"],
  "scheme.who": ["Who it is for", "यह किसके लिए है"],
  "scheme.benefits": ["What it covers", "इसमें क्या शामिल है"],
  "scheme.evidence": ["Evidence usually needed", "आमतौर पर जो प्रमाण चाहिए"],
  "scheme.source": ["Where this text comes from", "यह पाठ कहाँ से है"],
  "scheme.sourceBody": [
    "Extract of published Ministry of Tribal Affairs scholarship material. Rule version {version}. This is not the full guideline.",
    "जनजातीय कार्य मंत्रालय की प्रकाशित छात्रवृत्ति सामग्री का अंश। नियम संस्करण {version}। यह पूरी गाइडलाइन नहीं है।",
  ],
  "scheme.sourceLink": ["Ministry scholarship page", "मंत्रालय की छात्रवृत्ति पृष्ठ"],
  "scheme.check": ["Check my match", "मेरा मेल देखें"],
  "scheme.openApply": ["Prepare application", "आवेदन तैयार करें"],
  "scheme.infoOnly": [
    "Application processing for this scheme is not open here. You can still see your match.",
    "यहाँ इस योजना का आवेदन प्रक्रिया खुली नहीं है। मेल फिर भी देख सकते हैं।",
  ],
  "scheme.readinessOnly": [
    "This path is a readiness check. It does not submit an award application and does not mean you will be selected.",
    "यह रास्ता तैयारी की जाँच है। यह पुरस्कार आवेदन नहीं भेजता और चयन का मतलब नहीं है।",
  ],
  "scheme.route": ["Where a student applies", "छात्र कहाँ आवेदन करता है"],
  "scheme.routeNote": [
    "This is the public portal for the scheme. JANMARG does not sign in there.",
    "यह योजना का सार्वजनिक पोर्टल है। JANMARG वहाँ साइन इन नहीं करता।",
  ],
  "scheme.path": ["How a file moves", "फ़ाइल कैसे आगे बढ़ती है"],
  "scheme.pathNote": [
    "Institute, then district, then the state, then bank credit after sanction. A quiet source is not a rejection. This desk does not pay.",
    "पहले संस्थान, फिर जिला, फिर राज्य, संस्वीकृति के बाद बैंक में जमा। स्रोत का चुप रहना अस्वीकृति नहीं है। यह डेस्क भुगतान नहीं करता।",
  ],
  "scheme.path.1": ["Institute checks admission and papers", "संस्थान दाखिला और कागज़ जाँचता है"],
  "scheme.path.2": ["District checks community and income", "जिला जनजाति और आय जाँचता है"],
  "scheme.path.3": ["State sanctions the list", "राज्य सूची संस्वीकृत करता है"],
  "scheme.path.4": ["Bank credit only after sanction", "बैंक में जमा केवल संस्वीकृति के बाद"],
  "scheme.portal.preMatric": ["DBT Tribal or the state portal", "डीबीटी ट्राइबल या राज्य पोर्टल"],
  "scheme.portal.postMatric": ["DBT Tribal portal", "डीबीटी ट्राइबल पोर्टल"],
  "scheme.portal.topClass": ["National Scholarship Portal", "राष्ट्रीय छात्रवृत्ति पोर्टल"],
  "scheme.portal.nfst": ["National Fellowship portal", "राष्ट्रीय फेलोशिप पोर्टल"],
  "scheme.portal.nos": ["National Overseas Scholarship portal", "राष्ट्रीय विदेशी छात्रवृत्ति पोर्टल"],
  "scheme.sample": [
    "The ministry page fetched on 29 Sep 2026 says 246 premier institutes. This desk checks a small sample, not that full list.",
    "29 सितंबर 2026 को मंत्रालय पृष्ठ पर 246 प्रमुख संस्थान लिखे हैं। यह डेस्क एक छोटा नमूना जाँचता है, पूरी सूची नहीं।",
  ],
  "scheme.quoted": ["From the ministry page", "मंत्रालय पृष्ठ से"],
  "scheme.quotedOn": ["Fetched 29 Sep 2026. This desk does not pay these amounts.", "29 सितंबर 2026 को लिया गया। यह डेस्क ये राशियाँ नहीं देती।"],
  "scheme.preMatric.name": ["Pre-Matric Scholarship", "प्री-मैट्रिक छात्रवृत्ति"],
  "scheme.preMatric.who": [
    "ST students in Class 9 and Class 10, within the income ceiling.",
    "कक्षा 9 और 10 के अनुसूचित जनजाति छात्र, आय सीमा के अंदर।",
  ],
  "scheme.preMatric.benefits": [
    "Support aimed at helping students stay in school. Amounts follow the published scheme, not this desk.",
    "स्कूल में बने रहने में मदद के लिए सहायता। राशि प्रकाशित योजना के अनुसार है, इस डेस्क के अनुसार नहीं।",
  ],
  "scheme.preMatric.evidence": [
    "ST certificate, income certificate, and a marksheet.",
    "जनजाति प्रमाण पत्र, आय प्रमाण पत्र और अंकपत्र।",
  ],
  "scheme.postMatric.name": ["Post-Matric Scholarship", "पोस्ट-मैट्रिक छात्रवृत्ति"],
  "scheme.postMatric.who": [
    "ST students from Class 11 through post-graduation, with family income within ₹2.5 lakh a year in this extract.",
    "कक्षा 11 से स्नातकोत्तर तक अनुसूचित जनजाति छात्र, इस अंश में परिवार की आय ₹2.5 लाख प्रति वर्ष के अंदर।",
  ],
  "scheme.postMatric.benefits": [
    "Compulsory fees and a maintenance allowance, as published. This screen does not calculate a payment.",
    "अनिवार्य शुल्क और रखरखाव भत्ता, जैसा प्रकाशित है। यह स्क्रीन भुगतान नहीं गिनती।",
  ],
  "scheme.postMatric.evidence": [
    "ST certificate, current income certificate, marksheet, and admission proof.",
    "जनजाति प्रमाण पत्र, चालू आय प्रमाण पत्र, अंकपत्र और दाखिले का प्रमाण।",
  ],
  "scheme.topClass.name": ["Top Class Education", "टॉप क्लास शिक्षा"],
  "scheme.topClass.who": [
    "ST students in graduate or postgraduate courses at notified institutes, with family income within ₹6 lakh a year in this extract.",
    "अधिसूचित संस्थानों में स्नातक या स्नातकोत्तर पढ़ रहे अनुसूचित जनजाति छात्र, इस अंश में आय ₹6 लाख प्रति वर्ष के अंदर।",
  ],
  "scheme.topClass.benefits": [
    "Tuition and living support at notified institutes, as published. A match here is not an award.",
    "अधिसूचित संस्थानों में ट्यूशन और रहने की सहायता, जैसा प्रकाशित है। यहाँ का मेल पुरस्कार नहीं है।",
  ],
  "scheme.topClass.evidence": [
    "ST certificate, income certificate, marksheet, admission proof, and an institute certificate.",
    "जनजाति प्रमाण पत्र, आय प्रमाण पत्र, अंकपत्र, दाखिला प्रमाण और संस्थान प्रमाण।",
  ],
  "scheme.nfst.name": ["National Fellowship", "राष्ट्रीय फेलोशिप"],
  "scheme.nfst.who": [
    "ST students in MPhil or PhD. Selection rules apply. This desk does not run the fellowship process.",
    "एमफिल या पीएचडी में अनुसूचित जनजाति छात्र। चयन के नियम लागू होते हैं। यह फेलोशिप प्रक्रिया नहीं चलाता।",
  ],
  "scheme.nfst.benefits": [
    "Fellowship support for research study, as published. This desk does not promise a fellowship.",
    "शोध अध्ययन के लिए फेलोशिप सहायता, जैसा प्रकाशित है। यह फेलोशिप का वादा नहीं करता।",
  ],
  "scheme.nfst.evidence": [
    "ST certificate, academic record, and research qualification evidence.",
    "जनजाति प्रमाण पत्र, शैक्षणिक रिकॉर्ड और शोध योग्यता का प्रमाण।",
  ],
  "scheme.nos.name": ["National Overseas Scholarship", "राष्ट्रीय विदेशी छात्रवृत्ति"],
  "scheme.nos.who": [
    "ST students aiming for a master’s or PhD abroad. Slots are limited and selection is competitive.",
    "विदेश में मास्टर या पीएचडी चाहने वाले अनुसूचित जनजाति छात्र। सीटें सीमित हैं और चयन प्रतियोगी है।",
  ],
  "scheme.nos.benefits": [
    "Support for listed overseas study, as published. Readiness is not a selection.",
    "अनुमोदित विदेशी अध्ययन के लिए सहायता, जैसा प्रकाशित है। तैयारी चयन नहीं है।",
  ],
  "scheme.nos.evidence": [
    "ST certificate, income certificate, passport evidence, and an admission or offer letter.",
    "जनजाति प्रमाण पत्र, आय प्रमाण पत्र, पासपोर्ट प्रमाण और दाखिला या प्रस्ताव पत्र।",
  ],
  "status.likelyEligible": ["Likely eligible", "संभावित रूप से पात्र"],
  "status.needsEvidence": ["Needs evidence", "और प्रमाण चाहिए"],
  "status.notMatched": ["Not matched to current rule", "मौजूदा नियम से मेल नहीं"],
  "status.unavailable": ["Eligibility could not be checked", "पात्रता जाँची नहीं जा सकी"],
  "status.help.likelyEligible": [
    "The current rules fit so far. This is not a sanction.",
    "मौजूदा नियम अभी तक मेल खाते हैं। यह संस्वीकृति नहीं है।",
  ],
  "status.help.needsEvidence": [
    "Something is missing, out of date, or inconsistent. Fix that before you submit.",
    "कुछ कमी है, पुराना है, या मेल नहीं खाता। भेजने से पहले उसे ठीक करें।",
  ],
  "status.help.notMatched": [
    "A current rule does not fit. Read the failed line. This is not a personal rejection note.",
    "एक मौजूदा नियम नहीं बैठता। फिसली हुई पंक्ति पढ़ें। यह व्यक्तिगत अस्वीकृति पत्र नहीं है।",
  ],
  "status.help.unavailable": [
    "A source did not respond, so the result was not produced.",
    "एक स्रोत ने जवाब नहीं दिया, इसलिए परिणाम नहीं बना।",
  ],
  "elig.title": ["Your match", "आपका मेल"],
  "elig.matched": ["What fits", "क्या मेल खाता है"],
  "elig.unmet": ["What does not fit yet", "क्या अभी नहीं बैठता"],
  "elig.missing": ["Evidence still needed", "जो प्रमाण अभी चाहिए"],
  "elig.noneMissing": ["No document is listed as missing.", "कोई दस्तावेज़ कमी में नहीं है।"],
  "elig.noUnmet": ["No failed line on this rule version.", "इस नियम संस्करण पर कोई फिसली पंक्ति नहीं।"],
  "elig.noMatched": ["No line passed.", "कोई पंक्ति पूरी नहीं हुई।"],
  "elig.actions": ["What you can do", "आप क्या कर सकते हैं"],
  "elig.disclaimer": [
    "rule version {version}. This is an explanation, not a decision. The Ministry of Tribal Affairs or the implementing agency is the final authority. A likely match is not a sanction and not a payment.",
    "मौजूदा नियम संस्करण {version}। यह व्याख्या है, निर्णय नहीं। अंतिम अधिकार जनजातीय कार्य मंत्रालय या लागू करने वाली संस्था का है। संभावित मेल संस्वीकृति नहीं और भुगतान नहीं है।",
  ],
  "elig.nosBanner": [
    "Readiness only. You are not being told that an award is yours.",
    "केवल तैयारी। यह नहीं कहा जा रहा कि पुरस्कार आपका है।",
  ],
  "reason.community.ok": ["Scheduled Tribe status is on the profile.", "प्रोफ़ाइल पर अनुसूचित जनजाति स्थिति है।"],
  "reason.community.no": ["The profile is not marked Scheduled Tribe for this rule.", "इस नियम के लिए प्रोफ़ाइल अनुसूचित जनजाति नहीं है।"],
  "reason.community.unknown": ["Scheduled Tribe status is not confirmed yet.", "अनुसूचित जनजाति स्थिति अभी पक्की नहीं है।"],
  "reason.level.ok": ["Study stage ({level}) is covered.", "पढ़ाई का स्तर ({level}) शामिल है।"],
  "reason.level.no": ["Study stage ({level}) is outside this scheme.", "पढ़ाई का स्तर ({level}) इस योजना से बाहर है।"],
  "reason.income.ok": ["Family income is within the income ceiling of {ceiling}.", "परिवार की आय आय सीमा {ceiling} के अंदर है।"],
  "reason.income.no": ["Family income is above the income ceiling of {ceiling}.", "परिवार की आय आय सीमा {ceiling} से ऊपर है।"],
  "reason.institute.ok": ["The institute is in the notified sample.", "संस्थान अधिसूचित नमूने में है।"],
  "reason.institute.no": ["The institute is not in the notified sample.", "संस्थान अधिसूचित नमूने में नहीं है।"],
  "reason.exclusive.ok": ["No other central scholarship is marked active.", "कोई अन्य केंद्रीय छात्रवृत्ति सक्रिय नहीं है।"],
  "reason.exclusive.no": ["Another central scholarship is marked active.", "एक अन्य केंद्रीय छात्रवृत्ति सक्रिय है।"],
  "reason.goal.ok": ["Overseas study is the stated goal.", "विदेशी अध्ययन लक्ष्य के रूप में लिखा है।"],
  "reason.goal.no": ["Overseas study is not the stated goal.", "विदेशी अध्ययन लक्ष्य के रूप में नहीं है।"],
  "reason.doc.ok": ["{doc} is on file and current.", "{doc} फ़ाइल में है और चालू है।"],
  "reason.doc.missing": ["{doc} is not on file.", "{doc} फ़ाइल में नहीं है।"],
  "reason.doc.expired": ["{doc} is out of date.", "{doc} पुराना है।"],
  "reason.doc.mismatch": ["{doc} has a name mismatch.", "{doc} पर नाम मेल नहीं खाता।"],
  "reason.doc.pending": ["{doc} is still pending.", "{doc} अभी लंबित है।"],
  "reason.doc.revoked": ["Reuse permission for {doc} was revoked.", "{doc} की पुनर्उपयोग अनुमति वापस ली गई।"],
  "reason.source.down": ["A required source did not respond.", "एक ज़रूरी स्रोत ने जवाब नहीं दिया।"],
  "why.community": ["The scheme in this extract is for Scheduled Tribe students.", "इस अंश में योजना अनुसूचित जनजाति छात्रों के लिए है।"],
  "why.level": ["The scheme covers a different study stage.", "योजना पढ़ाई के दूसरे स्तर के लिए है।"],
  "why.income": ["Income above the ceiling does not match this rule version.", "सीमा से ऊपर आय इस नियम संस्करण से मेल नहीं खाती।"],
  "why.institute": ["Top Class here applies only to the seeded notified sample.", "यहाँ टॉप क्लास केवल अधिसूचित नमूने पर लागू है।"],
  "why.exclusive": ["A student is generally not meant to hold two central scholarships at once.", "आम तौर पर एक छात्र एक समय पर दो केंद्रीय छात्रवृत्ति नहीं लेता।"],
  "why.goal": ["Overseas readiness applies when study abroad is the goal.", "विदेशी तैयारी तब है जब विदेश में पढ़ाई लक्ष्य हो।"],
  "why.expired": ["An out-of-date certificate stops the file before submission. Renew it. This is not a rejection.", "पुराना प्रमाण पत्र भेजने से पहले फ़ाइल रोकता है। उसे नया करें। यह अस्वीकृति नहीं है।"],
  "why.mismatch": ["The marksheet name and the profile name differ, so verification waits. This is not a rejection.", "अंकपत्र और प्रोफ़ाइल के नाम अलग हैं, इसलिए सत्यापन रुकता है। यह अस्वीकृति नहीं है।"],
  "why.missing": ["The file needs this evidence before it can move. Missing evidence is not a decision.", "आगे बढ़ने से पहले यह प्रमाण चाहिए। कमी कोई फैसला नहीं है।"],
  "why.offer": ["Without an admission offer, overseas readiness stays incomplete. An offer is not a selection.", "दाखिला प्रस्ताव के बिना विदेशी तैयारी अधूरी रहती है। प्रस्ताव चयन नहीं है।"],
  "why.passport": ["Passport evidence is part of the overseas checklist. It does not award the scholarship.", "पासपोर्ट प्रमाण विदेशी जाँच-सूची का हिस्सा है। यह छात्रवृत्ति नहीं देता।"],
  "why.revoked": ["You withdrew permission to reuse this copy. Allow it again if you want it used.", "आपने इस प्रति के पुनर्उपयोग की अनुमति वापस ली। उपयोग करना हो तो फिर दें।"],
  "why.qualification": ["Fellowship readiness here asks for research qualification evidence.", "यहाँ फेलोशिप तैयारी शोध योग्यता का प्रमाण माँगती है।"],
  "why.source": ["Eligibility could not be checked because a connector did not respond.", "कनेक्टर ने जवाब नहीं दिया, इसलिए पात्रता जाँची नहीं जा सकी।"],
  "doc.casteCertificate": ["ST certificate", "जनजाति प्रमाण पत्र"],
  "doc.incomeCertificate": ["Income certificate", "आय प्रमाण पत्र"],
  "doc.marksheet": ["Marksheet", "अंकपत्र"],
  "doc.admissionProof": ["Admission proof", "दाखिले का प्रमाण"],
  "doc.instituteCertificate": ["Institute certificate", "संस्थान प्रमाण पत्र"],
  "doc.passport": ["Passport", "पासपोर्ट"],
  "doc.overseasOffer": ["Overseas offer", "विदेशी प्रस्ताव"],
  "doc.researchQualification": ["Research qualification", "शोध योग्यता"],
  "level.class9": ["Class 9", "कक्षा 9"],
  "level.class10": ["Class 10", "कक्षा 10"],
  "level.class11": ["Class 11", "कक्षा 11"],
  "level.class12": ["Class 12", "कक्षा 12"],
  "level.ug": ["Undergraduate", "स्नातक"],
  "level.pg": ["Postgraduate", "स्नातकोत्तर"],
  "level.research": ["MPhil or PhD", "एमफिल या पीएचडी"],
  "level.overseasMasters": ["Master’s abroad", "विदेश में मास्टर"],
  "level.overseasPhd": ["PhD abroad", "विदेश में पीएचडी"],
  "docs.title": ["Document passport", "दस्तावेज़ पासपोर्ट"],
  "docs.intro": [
    "Copies stored for reuse. Each one shows where it came from, whether it is current, and which schemes can use it.",
    "पुनर्उपयोग के लिए सहेजी प्रतियाँ। हर एक बताता है वह कहाँ से आया, चालू है या नहीं, और किन योजनाओं में लग सकता है।",
  ],
  "docs.connect": ["Connect document locker", "दस्तावेज़ लॉकर जोड़ें"],
  "docs.empty": ["No documents are in the passport yet.", "पासपोर्ट में अभी कोई दस्तावेज़ नहीं है।"],
  "docs.expiry": ["Valid until {date}", "{date} तक वैध"],
  "docs.noExpiry": ["No expiry date on file", "फ़ाइल पर समाप्ति तिथि नहीं"],
  "docs.reuse": ["Reusable for", "इनमें पुनर्उपयोग"],
  "docs.maps": ["Fills these fields", "ये फ़ील्ड भरता है"],
  "docs.ref": ["Reference", "संदर्भ"],
  "docs.consentOn": ["Reuse allowed", "पुनर्उपयोग की अनुमति है"],
  "docs.consentOff": ["Reuse not allowed", "पुनर्उपयोग की अनुमति नहीं"],
  "docs.importBody": [
    "This is a document locker, not live DigiLocker. Allow a copy only if you want it in the passport.",
    "यह दस्तावेज़ लॉकर है, लाइव DigiLocker नहीं। प्रति तभी लें जब आप उसे पासपोर्ट में चाहते हों।",
  ],
  "docs.allow": ["Allow the to copy selected documents", "को चुने दस्तावेज़ कॉपी करने दें"],
  "docs.pull": ["Copy into passport", "पासपोर्ट में कॉपी करें"],
  "docs.denied": ["Consent was not given, so nothing was copied.", "सहमति नहीं मिली, इसलिए कुछ कॉपी नहीं हुआ।"],
  "docs.unavailable": ["The document locker did not respond. Nothing was copied.", "दस्तावेज़ लॉकर ने जवाब नहीं दिया। कुछ कॉपी नहीं हुआ।"],
  "docs.imported": ["Copied into the passport from the document locker.", "दस्तावेज़ लॉकर से पासपोर्ट में कॉपी हो गया।"],
  "docs.lockerEmpty": ["No new document is waiting in the document locker.", "दस्तावेज़ लॉकर में कोई नया दस्तावेज़ नहीं है।"],
  "docs.renew": ["Replace with a fresh certificate", "नए प्रमाण पत्र से बदलें"],
  "docs.renewed": ["Income certificate replaced. It is current here.", "आय प्रमाण पत्र बदल दिया। यहाँ यह चालू है।"],
  "docs.revoke": ["Revoke document locker reuse", "दस्तावेज़ लॉकर पुनर्उपयोग वापस लें"],
  "docs.revoked": ["document locker copies can no longer be reused.", "दस्तावेज़ लॉकर प्रतियाँ अब पुनर्उपयोग नहीं हो सकतीं।"],
  "docs.noAadhaar": ["Aadhaar numbers and bank accounts are not collected.", "आधार संख्या और बैंक खाता नहीं लिए जाते।"],
  "ver.verified": ["Verified", "जाँचा हुआ"],
  "ver.mismatch": ["Name mismatch", "नाम मेल नहीं"],
  "ver.pending": ["Pending", "लंबित"],
  "ver.unavailable": ["Unavailable", "उपलब्ध नहीं"],
  "ver.expired": ["Out of date", "पुराना"],
  "ver.title": ["Verification centre", "सत्यापन केंद्र"],
  "ver.layer": ["One check, many sources", "एक जाँच, कई स्रोत"],
  "ver.layerBody": ["Each row is a check. A mismatch goes to review. It does not close the file. A missing or expired paper still needs you.", "हर पंक्ति एक जाँच है। नाम या रिकॉर्ड का अंतर समीक्षा में जाता है। फ़ाइल बंद नहीं होती। पुराना या गायब कागज़ आपको ही लगाना है।"],
  "ver.run": ["Run the check", "जाँच चलाएँ"],
  "layer.identity": ["Identity name", "पहचान का नाम"],
  "layer.st": ["ST certificate", "जनजाति प्रमाण पत्र"],
  "layer.pvtg": ["PVTG marker", "पीवीटीजी चिह्न"],
  "layer.academic": ["Academic record", "शैक्षणिक रिकॉर्ड"],
  "layer.institutionSchool": ["School enrolment", "स्कूल नामांकन"],
  "layer.institutionHigher": ["Institution", "संस्थान"],
  "layer.net": ["NET or JRF", "नेट या जेआरएफ"],
  "layer.disability": ["Disability certificate", "दिव्यांगता प्रमाण पत्र"],
  "layer.income": ["Income certificate", "आय प्रमाण पत्र"],
  "layer.domicile": ["Domicile", "निवास"],
  "layer.src.identity": ["Profile compared with the marksheet", "प्रोफ़ाइल की अंकपत्र से तुलना"],
  "layer.src.st": ["Document passport, ST certificate", "दस्तावेज़ पासपोर्ट, जनजाति प्रमाण पत्र"],
  "layer.src.pvtg": ["Not marked on this file", "इस फ़ाइल पर चिह्न नहीं"],
  "layer.src.academic": ["Academic record", "शैक्षणिक रिकॉर्ड"],
  "layer.src.institutionSchool": ["School enrolment record", "स्कूल नामांकन रिकॉर्ड"],
  "layer.src.institutionHigher": ["Institute record, not live AISHE", "संस्थान रिकॉर्ड, लाइव एआईएसएचई नहीं"],
  "layer.src.net": ["Qualification record", "योग्यता रिकॉर्ड"],
  "layer.src.disability": ["Not on this file", "इस फ़ाइल पर नहीं"],
  "layer.src.income": ["Income certificate on this file", "इस फ़ाइल का आय प्रमाण पत्र"],
  "layer.src.domicile": ["State on the profile, not a live domicile pull", "प्रोफ़ाइल का राज्य, लाइव निवास पुल नहीं"],
  "layer.matched": ["Matched", "मेल खाता है"],
  "layer.mismatch": ["Mismatch, sent to review", "अंतर, समीक्षा में"],
  "layer.notFound": ["Needs a paper from you", "आपसे कागज़ चाहिए"],
  "layer.sourceUnavailable": ["Source did not answer", "स्रोत ने जवाब नहीं दिया"],
  "layer.notApplicable": ["Not used on this file", "इस फ़ाइल पर लागू नहीं"],
  "layer.reuse": ["Reuse", "दोबारा उपयोग"],
  "layer.manualReview": ["Manual review", "मैनुअल समीक्षा"],
  "layer.studentAction": ["Your step", "आपका कदम"],
  "layer.skip": ["Skipped", "छोड़ा गया"],
  "ver.intro": [
    "Compare sources. If they disagree, you will see the field, both values, and what to do.",
    "स्रोतों की तुलना करें। अगर वे अलग हों, तो फ़ील्ड, दोनों मान, और आगे का कदम दिखेगा।",
  ],
  "ver.sources": ["Connector status", "कनेक्टर स्थिति"],
  "ver.available": ["Responding here", "यहाँ जवाब दे रहा है"],
  "ver.down": ["Not responding", "जवाब नहीं दे रहा"],
  "ver.noMismatch": ["No name mismatch on this file.", "इस फ़ाइल पर नाम का अंतर नहीं है।"],
  "ver.compare": ["Name comparison", "नाम की तुलना"],
  "ver.profile": ["Profile", "प्रोफ़ाइल"],
  "ver.marksheet": ["Marksheet", "अंकपत्र"],
  "ver.other": ["Other copy", "अन्य प्रति"],
  "ver.autoYes": ["Extra spaces or dots can be cleaned up without a reviewer.", "अतिरिक्त स्पेस या बिंदु समीक्षक के बिना साफ हो सकते हैं।"],
  "ver.autoNo": ["This spelling difference cannot be cleaned up automatically.", "यह वर्तनी अंतर अपने आप साफ नहीं हो सकता।"],
  "ver.manualYes": ["A person would need to review it if you do not correct a side.", "अगर आप एक पक्ष नहीं सुधारते, तो किसी व्यक्ति को समीक्षा करनी होगी।"],
  "ver.manualNo": ["Manual review is not required for this difference.", "इस अंतर के लिए मैनुअल समीक्षा ज़रूरी नहीं।"],
  "ver.why": ["Why it matters", "यह क्यों मायने रखता है"],
  "ver.whyBody": [
    "Institute checks compare the marksheet name with the profile. A difference pauses the file. It does not reject it.",
    "संस्थान जाँच अंकपत्र के नाम की तुलना प्रोफ़ाइल से करती है। अंतर फ़ाइल रोकता है। अस्वीकार नहीं करता।",
  ],
  "ver.useRegistry": ["Update my profile to the marksheet name", "प्रोफ़ाइल को अंकपत्र वाले नाम पर लाएँ"],
  "ver.aligned": ["Profile updated to the marksheet name. You confirmed this change.", "प्रोफ़ाइल अंकपत्र वाले नाम पर आ गई। यह बदलाव आपने पक्का किया।"],
  "ver.review": ["Keep my profile name and ask for review", "प्रोफ़ाइल नाम रखें और समीक्षा माँगें"],
  "ver.reviewed": [
    "Sent to the review queue. No officer decision is made automatically.",
    "समीक्षा कतार में भेज दिया। कोई अधिकारी फैसला अपने आप नहीं होता।",
  ],
  "ver.inReview": ["Manual review has been requested.", "मैनुअल समीक्षा माँगी जा चुकी है।"],
  "ver.pull": ["Refresh academic record", "शैक्षणिक रिकॉर्ड फिर लाएँ"],
  "ver.pullFail": ["The academic record did not respond.", "शैक्षणिक रिकॉर्ड ने जवाब नहीं दिया।"],
  "src.identity": ["Identity record", "पहचान रिकॉर्ड"],
  "src.digilocker": ["Document locker", "दस्तावेज़ लॉकर"],
  "src.academic": ["Academic record", "शैक्षणिक रिकॉर्ड"],
  "src.portal": ["Scheme portal", "योजना पोर्टल"],
  "prov.userEntered": ["You entered", "आपने भरा"],
  "prov.digilockerMock": ["Document locker", "दस्तावेज़ लॉकर"],
  "prov.academicRegistryMock": ["Academic record", "शैक्षणिक रिकॉर्ड"],
  "prov.institutionMock": ["Institute record", "संस्थान रिकॉर्ड"],
  "field.legalName": ["Name", "नाम"],
  "field.birthYear": ["Year of birth", "जन्म वर्ष"],
  "field.stStatus": ["Community status", "समुदाय स्थिति"],
  "field.place": ["Place", "स्थान"],
  "field.studyLevel": ["Study stage", "पढ़ाई का स्तर"],
  "field.institution": ["Institute", "संस्थान"],
  "field.course": ["Course", "पाठ्यक्रम"],
  "field.income": ["Family income", "परिवार की आय"],
  "field.mobile": ["Mobile", "मोबाइल"],
  "field.other": ["Other central scholarship", "अन्य केंद्रीय छात्रवृत्ति"],
  "st.st": ["Scheduled Tribe", "अनुसूचित जनजाति"],
  "st.notSt": ["Not marked ST", "एसटी चिह्नित नहीं"],
  "st.unknown": ["Not confirmed", "पक्का नहीं"],
  "yes": ["Yes", "हाँ"],
  "no": ["No", "नहीं"],
  "wiz.title": ["Application", "आवेदन"],
  "wiz.profile": ["Your details", "आपका विवरण"],
  "wiz.docs": ["Documents to reuse", "पुनर्उपयोग के दस्तावेज़"],
  "wiz.institute": ["Institute", "संस्थान"],
  "wiz.review": ["Review", "जाँच"],
  "wiz.prefilled": ["Filled from your profile. The source of each field is shown.", "प्रोफ़ाइल से भरा गया। हर फ़ील्ड का स्रोत दिखाया है।"],
  "wiz.pickDocs": ["Choose current documents you allow this application to reuse.", "वे चालू दस्तावेज़ चुनें जिन्हें इस आवेदन में पुनर्उपयोग की अनुमति है।"],
  "wiz.noReuse": ["No reusable document is ready for this scheme.", "इस योजना के लिए कोई पुनर्उपयोग दस्तावेज़ तैयार नहीं है।"],
  "wiz.confirmInstitute": ["The institute details above are the ones I want on this file.", "ऊपर का संस्थान विवरण इसी फ़ाइल पर चाहिए।"],
  "wiz.submit": ["Submit application", "आवेदन भेजें"],
  "wiz.reviewNote": ["The name difference is with a reviewer. The file was still stored. This is not a rejection.", "नाम का अंतर समीक्षा में है। फ़ाइल फिर भी सहेज ली गई। यह अस्वीकृति नहीं है।"],
  "wiz.receipt": ["receipt {id}", "रसीद {id}"],
  "wiz.receiptNote": [
    "This is not an NSP or ministry acknowledgement. No funds were sanctioned.",
    "यह एनएसपी या मंत्रालय की पावती नहीं है। कोई धन संस्वीकृत नहीं हुआ।",
  ],
  "wiz.seeJourney": ["See the timeline", "समयरेखा देखें"],
  "wiz.closed": ["This scheme cannot be submitted from here.", "यह योजना यहाँ से जमा नहीं हो सकती।"],
  "wiz.readiness": ["Overseas readiness does not submit an application from this screen.", "विदेशी तैयारी इस स्क्रीन से आवेदन नहीं भेजती।"],
  "wiz.offline": ["You are offline. The draft stays on this phone. Submit when you reconnect.", "आप ऑफ़लाइन हैं। मसौदा इस फ़ोन पर रहेगा। जुड़ने पर भेजें।"],
  "val.offline": ["You are offline, so the file was not sent.", "आप ऑफ़लाइन हैं, इसलिए फ़ाइल नहीं भेजी गई।"],
  "val.sourceUnavailable": ["The portal did not respond. Nothing was sent.", "पोर्टल ने जवाब नहीं दिया। कुछ नहीं भेजा गया।"],
  "val.schemeClosed": ["Full processing is not open for this scheme.", "इस योजना की पूरी प्रक्रिया खुली नहीं है।"],
  "val.readinessOnly": ["This is a readiness flow. It cannot be submitted as an award.", "यह तैयारी प्रवाह है। इसे पुरस्कार के रूप में नहीं भेजा जा सकता।"],
  "val.alreadySubmitted": ["A file for this scheme is already open.", "इस योजना की फ़ाइल पहले से खुली है।"],
  "val.exclusive": ["One central scholarship at a time. Close the other file before starting this one.", "एक समय में एक केंद्रीय छात्रवृत्ति। इसे शुरू करने से पहले दूसरी फ़ाइल बंद करें।"],
  "val.instituteUnconfirmed": ["Confirm the institute before you submit.", "भेजने से पहले संस्थान पक्का करें।"],
  "val.expiredDoc": ["An expired document is still on the file. Replace it first.", "फ़ाइल पर एक पुराना दस्तावेज़ है। पहले उसे बदलें।"],
  "val.mismatch": ["The name still does not match. Resolve it before the submit.", "नाम अभी भी मेल नहीं खाता। भेजने से पहले सुलझाएँ।"],
  "val.missingDoc": ["A required document was not selected.", "एक ज़रूरी दस्तावेज़ नहीं चुना गया।"],
  "val.consent": ["A selected document does not have reuse permission.", "चुने दस्तावेज़ पर पुनर्उपयोग की अनुमति नहीं है।"],
  "val.notReady": ["The match is not clear yet. Read the failed lines first.", "मेल अभी साफ नहीं है। पहले फिसली पंक्तियाँ पढ़ें।"],
  "jny.title": ["Journey", "यात्रा"],
  "jny.now": ["Current status", "अभी की स्थिति"],
  "jny.owner": ["Next owner", "अगला मालिक"],
  "jny.next": ["Next action", "अगला काम"],
  "jny.latest": ["Latest event", "ताज़ा घटना"],
  "jny.updated": ["Last updated {date}", "आखिरी बदलाव {date}"],
  "jny.reason": ["Reason recorded", "दर्ज कारण"],
  "track.submission": ["Submission", "आवेदन"],
  "track.verification": ["Verification", "जाँच"],
  "track.sanction": ["Sanction", "संस्वीकृति"],
  "track.disbursement": ["Disbursement", "भुगतान"],
  "track.done": ["Done", "हो गया"],
  "track.now": ["Here", "यहीं"],
  "track.later": ["Not yet", "अभी नहीं"],
  "track.stopped": ["Stopped", "रुका"],
  "track.note": ["Sanction and bank credit stay empty until that step exists. Checking status does not move money.", "संस्वीकृति और बैंक जमा तब तक खाली रहते हैं जब तक वह कदम न हो। स्थिति देखने से पैसा नहीं चलता।"],
  "home.noCredit": ["No credit is on file for this student. Money has not moved.", "इस छात्र की फ़ाइल पर कोई जमा नहीं है। पैसा नहीं चला।"],
  "home.window": ["Top Class applications on NSP are open until 31 Oct 2026.", "एनएसपी पर टॉप क्लास आवेदन 31 अक्टूबर 2026 तक खुले हैं।"],
  "home.ledgerNote": ["Payment rows for this student.", "इस छात्र की भुगतान पंक्तियाँ।"],
  "jny.delayed": ["The portal has not moved this file yet. That delay is not a rejection.", "पोर्टल ने फ़ाइल अभी नहीं बढ़ाई। यह देरी अस्वीकृति नहीं है।"],
  "jny.advanced": ["The institute now holds the file.", "अब फ़ाइल संस्थान के पास है।"],
  "jny.empty": ["No application is open yet.", "अभी कोई आवेदन खुला नहीं है।"],
  "jny.down": ["Status could not be refreshed. The last saved events are below.", "स्थिति नई नहीं हो सकी। आखिरी सहेजी घटनाएँ नीचे हैं।"],
  "app.draft": ["Draft", "मसौदा"],
  "app.submitted": ["Submitted", "भेजा गया"],
  "app.instituteVerification": ["Institute verification", "संस्थान सत्यापन"],
  "app.stateVerification": ["State verification", "राज्य सत्यापन"],
  "app.ministryReview": ["Ministry review", "मंत्रालय समीक्षा"],
  "app.sanctioned": ["Sanctioned", "संस्वीकृत"],
  "app.disbursed": ["Disbursed", "भुगतान हुआ"],
  "app.returned": ["Returned", "वापस"],
  "app.rejected": ["Not accepted", "स्वीकार नहीं"],
  "owner.student": ["You", "आप"],
  "owner.institute": ["Institute", "संस्थान"],
  "owner.state": ["State team", "राज्य टीम"],
  "owner.ministry": ["Ministry team", "मंत्रालय टीम"],
  "owner.system": ["system", "सिस्टम"],
  "next.submitted": ["Wait, then check status again. The institute has not confirmed the next step.", "रुकें, फिर स्थिति देखें। संस्थान ने अगला कदम पक्का नहीं किया।"],
  "next.instituteVerification": ["The institute holds the next step.", "अगला कदम संस्थान के पास है।"],
  "next.returned": ["Read the reason, fix the evidence, and only then try again.", "कारण पढ़ें, प्रमाण ठीक करें, और तभी फिर कोशिश करें।"],
  "next.rejected": ["Read the reason. This desk does not reopen a closed file by itself.", "कारण पढ़ें। यह बंद फ़ाइल अपने आप नहीं खोलता।"],
  "next.other": ["Watch the timeline. No payment is made from this screen.", "समयरेखा देखें। इस स्क्रीन से कोई भुगतान नहीं होता।"],
  "event.submitted.title": ["Application stored", "आवेदन सहेजा गया"],
  "event.submitted.body": ["You sent a file. It is not a government acknowledgement.", "आपने फ़ाइल भेजी। यह सरकारी पावती नहीं है।"],
  "event.delayed.title": ["Waiting on the portal", "पोर्टल का इंतज़ार"],
  "event.delayed.body": ["The next step has not been confirmed. This delay is not a rejection.", "अगला कदम पक्का नहीं हुआ। यह देरी अस्वीकृति नहीं है।"],
  "event.institute.title": ["The institute took the file", "संस्थान ने फ़ाइल ली"],
  "event.institute.body": ["Status moved to institute verification in the timeline only.", "स्थिति केवल समयरेखा में संस्थान सत्यापन पर गई।"],
  "event.state.title": ["The file moved one step", "फ़ाइल एक कदम आगे बढ़ी"],
  "event.state.body": ["The next desk has the file. Money has not moved.", "अगली डेस्क के पास फ़ाइल है। पैसा नहीं चला।"],
  "audit.viewDocs": ["The document wallet was opened.", "दस्तावेज़ वॉलेट खोला गया।"],
  "jago.title": ["JAGO", "JAGO"],
  "jago.demoRetrieval": ["", ""],
  "jago.intro": [
    "Ask in simple words. Answers come only from the desk’s official extracts. If I cannot verify it, I will say so.",
    "सरल शब्दों में पूछें। जवाब केवल डेस्क के आधिकारिक अंशों से आते हैं। अगर मैं जाँच नहीं कर सकूँ, तो कहूँगा/कहूँगी।",
  ],
  "jago.placeholder": ["Ask JAGO", "JAGO से पूछें"],
  "jago.ask": ["Ask", "पूछें"],
  "jago.next": ["What to do next", "आगे क्या करें"],
  "jago.sources": ["Source", "स्रोत"],
  "jago.voice": ["Speak", "बोलें"],
  "jago.help": ["Raise a help request", "सहायता अनुरोध दर्ज करें"],
  "jago.helped": ["Help request saved on this phone. No government desk was contacted.", "सहायता अनुरोध इस फ़ोन पर सहेजा गया। किसी सरकारी डेस्क से संपर्क नहीं हुआ।"],
  "jago.fallback": [
    "I could not verify this from the current official sources. Please raise a help request.",
    "मैं इसे मौजूदा आधिकारिक स्रोतों से जाँच नहीं सकी। कृपया सहायता अनुरोध दर्ज करें।",
  ],
  "jago.suggest1": ["What is the income limit for post-matric?", "पोस्ट-मैट्रिक की आय सीमा क्या है?"],
  "jago.suggest2": ["What if my income certificate is expired?", "अगर आय प्रमाण पत्र पुराना हो तो?"],
  "jago.suggest3": ["Will I get the scholarship money?", "क्या मुझे छात्रवृत्ति का पैसा मिलेगा?"],
  "jago.suggest4": ["What does overseas readiness need?", "विदेशी तैयारी में क्या चाहिए?"],
  "off.title": ["Officer insights", "अधिकारी झलक"],
  "off.deniedTitle": ["Officer view is closed", "अधिकारी दृश्य बंद है"],
  "off.deniedBody": [
    "Students do not see this desk. It is a role for aggregate figures only. It cannot sanction or reject anyone.",
    "छात्र यह डेस्क नहीं देखते। यह केवल कुल आँकड़ों की भूमिका है। यह किसी को संस्वीकृत या अस्वीकार नहीं कर सकती।",
  ],
  "off.openDemo": ["Open officer view", "अधिकारी दृश्य खोलें"],
  "off.backStudent": ["Return to student view", "छात्र दृश्य पर लौटें"],
  "off.demoNote": ["School register on this desk. Counts only.", "इस डेस्क का स्कूल रजिस्टर। केवल गिनती।"],
  "off.pending": ["Pending verification", "लंबित सत्यापन"],
  "off.expired": ["Expired income certificates", "पुराने आय प्रमाण पत्र"],
  "off.funnel": ["Scheme funnel", "योजना फ़नल"],
  "off.coverage": ["District coverage", "ज़िला कवरेज"],
  "off.unreached": ["Enrolled but not registered", "दाखिल लेकिन पंजीकृत नहीं"],
  "off.matchNote": ["School row matched to an APAAR-style id and one-time registration. No student names.", "स्कूल पंक्ति का मेल आपार-जैसे आईडी और वन-टाइम रजिस्ट्रेशन से। छात्र के नाम नहीं।"],
  "off.noDecision": ["This screen cannot sanction, reject, or pay anyone.", "यह स्क्रीन किसी को संस्वीकृत, अस्वीकार या भुगतान नहीं कर सकती।"],
  "off.reason.no_apaar": ["Enrolled. No APAAR-style id, so the file cannot be matched.", "दाखिला है। आपार-जैसे आईडी नहीं, इसलिए फ़ाइल नहीं मिलती।"],
  "off.reason.no_otr": ["APAAR-style id is present. One-time registration is missing.", "आपार-जैसे आईडी है। वन-टाइम रजिस्ट्रेशन नहीं है।"],
  "off.reason.no_scholarship": ["Enrolled and the identifiers match. No scholarship registration.", "दाखिला है और पहचान मिलती है। छात्रवृत्ति पंजीकरण नहीं है।"],
  "off.enrolled": ["Enrolled {count}", "नामांकित {count}"],
  "off.apaar": ["With an APAAR-style id {count}", "आपार-जैसे आईडी के साथ {count}"],
  "off.otr": ["With one-time registration {count}", "वन-टाइम रजिस्ट्रेशन के साथ {count}"],
  "off.seed": ["Inside this desk’s five files", "इस डेस्क की पाँच फ़ाइलों में"],
  "off.seedExpired": ["Expired documents", "पुराने दस्तावेज़"],
  "off.seedMismatch": ["Name mismatches", "नाम के अंतर"],
  "off.seedDrafts": ["Unsent drafts", "न भेजे मसौदे"],
  "off.seedReview": ["Open manual reviews", "खुली मैनुअल समीक्षा"],
  "off.gap": ["Gap {count}", "अंतर {count}"],
  "off.covered": ["{count}% with a registration signal", "{count}% पर पंजीकरण संकेत"],
  "off.funnel.seen": ["Saw the desk", "डेस्क देखी"],
  "off.funnel.matched": ["Rules matched", "नियम मेल खाए"],
  "off.funnel.submitted": ["submitted", "भेजा"],
  "off.funnel.pending": ["Still pending", "अभी लंबित"],
  "int.title": ["Integration health", "इंटीग्रेशन स्वास्थ्य"],
  "int.body": ["One gateway. Nine connectors. This build runs the adapter for each. An official adapter replaces it without changing this screen. Nothing here is a live government session.", "एक गेटवे। नौ कनेक्टर। यह बिल्ड हर एक का एडाप्टर चलाता है। आधिकारिक एडाप्टर इसी स्क्रीन को बदले बिना लग सकता है। यहाँ कोई लाइव सरकारी सत्र नहीं है।"],
  "int.empty": ["Check the connectors to see mode, time, and status for this file.", "इस फ़ाइल का मोड, समय और स्थिति देखने के लिए कनेक्टर जाँचें।"],
  "int.refresh": ["Check connectors", "कनेक्टर जाँचें"],
  "int.mock": ["adapter", "एडाप्टर"],
  "int.official": ["Official connector", "आधिकारिक कनेक्टर"],
  "int.nsp": ["NSP", "एनएसपी"],
  "int.sfmp": ["Canara SFMP", "केनरा एसएफएमपी"],
  "int.nfst": ["NFST", "एनएफएसटी"],
  "int.nos": ["NOS", "एनओएस"],
  "int.digilocker": ["DigiLocker", "डिजिलॉकर"],
  "int.apaar": ["APAAR", "आपार"],
  "int.udise": ["UDISE+", "यूडाइज+"],
  "int.aishe": ["AISHE", "एआईएसएचई"],
  "int.dbt": ["DBT / PFMS", "डीबीटी / पीएफएमएस"],
  "int.tone.healthy": ["Healthy", "ठीक"],
  "int.tone.match": ["Match", "मेल"],
  "int.tone.mismatch": ["Mismatch available", "अंतर मिला"],
  "int.tone.connected": ["Connected", "जुड़ा"],
  "int.tone.consent": ["Consent required", "सहमति चाहिए"],
  "int.tone.down": ["Did not answer", "जवाब नहीं"],
  "int.tone.reserved": ["Credentials not configured", "क्रेडेंशियल सेट नहीं"],
  "int.status.DEFECTIVE": ["The income certificate on this file is out of date.", "इस फ़ाइल का आय प्रमाण पत्र पुराना है।"],
  "int.status.RETURNED_FOR_REVIEW": ["The name does not match. It goes to review. The file is not closed.", "नाम मेल नहीं खाता। यह समीक्षा में जाता है। फ़ाइल बंद नहीं होती।"],
  "int.status.NOT_ON_THIS_PORTAL": ["This file is read on the overseas connector.", "यह फ़ाइल विदेशी कनेक्टर पर पढ़ी जाती है।"],
  "int.status.INSTITUTE_VERIFICATION": ["Institute step. Payment has not started. No money is sent.", "संस्थान का कदम। भुगतान शुरू नहीं हुआ। पैसा नहीं भेजा जाता।"],
  "int.status.NOT_SUBMITTED": ["Nothing has been sent on this connector.", "इस कनेक्टर पर कुछ नहीं भेजा गया।"],
  "int.status.NOT_APPLICABLE": ["This connector does not apply to this file.", "यह कनेक्टर इस फ़ाइल पर लागू नहीं।"],
  "int.status.READINESS": ["The overseas offer is still missing.", "विदेशी प्रस्ताव अभी नहीं है।"],
  "int.status.READY": ["The overseas offer is on the file.", "विदेशी प्रस्ताव फ़ाइल पर है।"],
  "int.status.CONNECTED": ["Ready. Documents already on the file can be reused.", "तैयार। फ़ाइल पर मौजूद दस्तावेज़ दोबारा इस्तेमाल हो सकते हैं।"],
  "int.status.MISMATCH": ["The record does not match. Review is open.", "रिकॉर्ड मेल नहीं खाता। समीक्षा खुली है।"],
  "int.status.MATCH": ["The record matches this file.", "रिकॉर्ड इस फ़ाइल से मेल खाता है।"],
  "int.status.NOT_A_SCHOOL_RECORD": ["This is not a school file. The institute connector is used instead.", "यह स्कूल फ़ाइल नहीं है। उसके बजाय संस्थान कनेक्टर है।"],
  "int.status.ENROLLED": ["School enrolment is on the record.", "स्कूल नामांकन रिकॉर्ड पर है।"],
  "int.status.RECOGNISED": ["The institute is in the sample.", "संस्थान नमूने में है।"],
  "int.status.NOT_IN_SAMPLE": ["The institute is not in the small sample.", "संस्थान छोटे नमूने में नहीं है।"],
  "int.status.NOT_INITIATED": ["Sanction, PFMS, bank check, then payment. This file has not started. No money moves.", "संस्वीकृति, पीएफएमएस, बैंक जाँच, फिर भुगतान। यह फ़ाइल शुरू नहीं हुई। पैसा नहीं चलता।"],
  "more.title": ["More", "और"],
  "more.profile": ["Profile", "प्रोफ़ाइल"],
  "more.verify": ["Verification centre", "सत्यापन केंद्र"],
  "more.integrations": ["Integration health", "इंटीग्रेशन स्वास्थ्य"],
  "more.officer": ["Officer insights", "अधिकारी झलक"],
  "more.documents": ["Documents", "दस्तावेज़"],
  "more.notifications": ["Notifications", "सूचनाएँ"],
  "more.settings": ["Settings", "सेटिंग्स"],
  "more.help": ["Help", "सहायता"],
  "more.how": ["Help", "सहायता"],
  "more.activity": ["Activity on this phone", "इस फ़ोन पर गतिविधि"],
  "more.connection": ["Network", "नेटवर्क"],
  "more.online": ["Online", "ऑनलाइन"],
  "more.offline": ["Offline", "ऑफ़लाइन"],
  "more.down": ["Source down", "स्रोत बंद"],
  "more.connectionHelp": [
    "Online keeps the file available. Offline keeps drafts on this phone. If a source does not respond, the file stays here.",
    "ऑनलाइन फ़ाइल उपलब्ध रखता है। ऑफ़लाइन मसौदा इस फ़ोन पर रहता है। अगर कोई स्रोत जवाब न दे, तो फ़ाइल यहीं रहती है।",
  ],
  "more.reset": ["Reset data", "डेटा रीसेट करें"],
  "more.resetDone": ["data reset on this phone.", "इस फ़ोन पर डेटा रीसेट हो गया।"],
  "more.signOut": ["Sign out", "साइन आउट"],
  "more.language": ["Language", "भाषा"],
  "prof.title": ["Profile", "प्रोफ़ाइल"],
  "prof.intro": ["Only the fields used for a match. Each one shows where it came from.", "केवल वे फ़ील्ड जो मेल के लिए हैं। हर एक बताता है वह कहाँ से आया।"],
  "prof.noAadhaar": ["Aadhaar and bank account are not collected here.", "यहाँ आधार और बैंक खाता नहीं लिए जाते।"],
  "how.title": ["Help", "सहायता"],
  "set.title": ["Settings", "सेटिंग्स"],
  "set.notices": ["Notices", "सूचनाएँ"],
  "set.students": ["Student file", "छात्र फ़ाइल"],
  "set.desk": ["Desk", "डेस्क"],
  "set.about": ["About JANMARG", "JANMARG के बारे में"],
  "set.aboutBody": ["One desk for five Ministry of Tribal Affairs schemes.", "जनजातीय कार्य मंत्रालय की पाँच योजनाओं के लिए एक डेस्क।"],
  "how.1": ["Your match is calculated from versioned rules, not by the chatbot.", "आपका मेल संस्करण वाले नियमों से गिना जाता है, चैटबॉट से नहीं।"],
  "how.2": ["JAGO answers only from official extracts and shows the source. If it is unsure, it says so.", "JAGO केवल आधिकारिक अंशों से जवाब देता है और स्रोत दिखाता है। अनिश्चित हो तो कह देता है।"],
  "how.3": ["Documents already on the file can be reused on the next application.", "फ़ाइल पर मौजूद दस्तावेज़ अगले आवेदन में फिर इस्तेमाल हो सकते हैं।"],
  "how.4": ["No Aadhaar, bank account, or real student data is stored.", "कोई आधार, बैंक खाता या असली छात्र डेटा नहीं है।"],
  "how.5": ["In the production design, the app calls an authenticated server function. Only that server holds secrets. The phone never holds a service key.", "उत्पादन डिज़ाइन में ऐप एक प्रमाणित सर्वर फ़ंक्शन को कॉल करता है। रहस्य केवल उस सर्वर पर रहते हैं। फ़ोन पर सेवा कुंजी नहीं होती।"],
  "how.6": ["Officer view shows totals only. It cannot reject or sanction a student.", "अधिकारी दृश्य केवल कुल आँकड़े दिखाता है। यह छात्र को अस्वीकार या संस्वीकृत नहीं कर सकता।"],
  "how.project": [
    "JANMARG is a unified desk for five Ministry of Tribal Affairs scholarship schemes.",
    "JANMARG जनजातीय कार्य मंत्रालय की पाँच छात्रवृत्ति योजनाओं की एक डेस्क है।",
  ],
  "note.title": ["Alerts", "सूचनाएँ"],
  "note.empty": ["No alerts. When a document or file changes, it will show here.", "कोई सूचना नहीं। दस्तावेज़ या फ़ाइल बदलेगी तो यहाँ दिखेगी।"],
  "note.mark": ["Mark read", "पढ़ लिया"],
  "note.high": ["Needs you", "आपकी ज़रूरत है"],
  "note.asha.title": ["Income certificate is out of date", "आय प्रमाण पत्र पुराना है"],
  "note.asha.body": ["Post-Matric cannot move until you replace it.", "जब तक आप इसे नहीं बदलते, पोस्ट-मैट्रिक नहीं बढ़ेगा।"],
  "note.birsa.title": ["Top Class match is ready to review", "टॉप क्लास मेल देखने के लिए तैयार है"],
  "note.birsa.body": ["You can reuse documents already in the passport.", "पासपोर्ट में जो दस्तावेज़ हैं, उन्हें फिर उपयोग कर सकते हैं।"],
  "note.meera.title": ["Overseas offer is still missing", "विदेशी प्रस्ताव अभी नहीं है"],
  "note.meera.body": ["Readiness stays incomplete. This is not a selection.", "तैयारी अधूरी है। यह चयन नहीं है।"],
  "note.dev.title": ["Marksheet name differs", "अंकपत्र का नाम अलग है"],
  "note.dev.body": ["Compare the two names before you submit anything.", "कुछ भेजने से पहले दोनों नाम तुलना करें।"],
  "note.nila.title": ["Your draft is still on this phone", "आपका मसौदा अभी इस फ़ोन पर है"],
  "note.nila.body": ["Resume it when you are ready. It was saved offline.", "तैयार हों तो जारी रखें। यह ऑफ़लाइन सहेजा गया था।"],
  "note.receipt.title": ["receipt created", "रसीद बन गई"],
  "note.receipt.body": ["Open the timeline. This is not a government acknowledgement.", "समयरेखा खोलें। यह सरकारी पावती नहीं है।"],
  "note.help.title": ["Help request saved", "सहायता अनुरोध सहेजा गया"],
  "note.help.body": ["It stays on this phone. No desk was contacted.", "यह इस फ़ोन पर है। किसी डेस्क से संपर्क नहीं हुआ।"],
  "audit.consent": ["You accepted the consent.", "आपने सहमति स्वीकार की।"],
  "audit.renewIncome": ["You replaced the income certificate.", "आपने आय प्रमाण पत्र बदला।"],
  "audit.alignName": ["You updated your name to the marksheet name.", "आपने नाम अंकपत्र वाले नाम पर किया।"],
  "audit.manualReview": ["You asked for a manual name review.", "आपने नाम की मैनुअल समीक्षा माँगी।"],
  "audit.reviewSubmit": ["The file was stored while the name difference stayed in review.", "नाम का अंतर समीक्षा में रहते हुए फ़ाइल सहेजी गई।"],
  "audit.import": ["You copied a document locker document.", "आपने दस्तावेज़ लॉकर दस्तावेज़ कॉपी किया।"],
  "audit.revoke": ["You revoked document locker reuse.", "आपने दस्तावेज़ लॉकर पुनर्उपयोग वापस लिया।"],
  "audit.draftSaved": ["A draft was saved on this phone.", "एक मसौदा इस फ़ोन पर सहेजा गया।"],
  "audit.submit": ["You sent a application.", "आपने आवेदन भेजा।"],
  "audit.help": ["You raised a help request.", "आपने सहायता अनुरोध दर्ज किया।"],
  "activity.empty": ["No activity yet.", "अभी कोई गतिविधि नहीं।"],
  "maps.legalName": ["Name", "नाम"],
  "maps.stStatus": ["Community status", "समुदाय स्थिति"],
  "maps.familyIncomeInr": ["Family income", "परिवार की आय"],
  "maps.studyLevel": ["Study stage", "पढ़ाई का स्तर"],
  "maps.institutionName": ["Institute", "संस्थान"],
  "maps.courseName": ["Course", "पाठ्यक्रम"],
  "state.loadingBody": ["Checking saved data.", "सहेजा डेटा देखा जा रहा है।"],
  "wiz.schemeClosedBody": ["You can still read the scheme and your match.", "योजना और अपना मेल फिर भी पढ़ सकते हैं।"],
} as const;

export type CopyKey = keyof typeof copy;

export function t(lang: Lang, key: string, vars?: Record<string, string | number>): string {
  const pair = (copy as Record<string, readonly [string, string]>)[key];
  const raw = pair ? (lang === "hi" ? pair[1] : pair[0]) : key;
  if (!vars) return raw;
  return raw.replace(/\{(\w+)\}/g, (_, name: string) => String(vars[name] ?? ""));
}

export function allCopyStrings(): string[] {
  return Object.values(copy).flatMap((pair) => [pair[0], pair[1]]);
}

export function copyPairCount(): number {
  return Object.keys(copy).length;
}
