/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IntegrationHealthRouteImport } from './routes/integration-health'
import { Route as JagoRouteImport } from './routes/jago'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManualReviewRouteImport } from './routes/manual-review'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyConsentRouteImport } from './routes/privacy-consent'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedGuidanceRouteImport } from './routes/saved-guidance'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyOnceRouteImport } from './routes/verify-once'
import { Route as AccountDeleteRouteImport } from './routes/account/delete'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminKnowledgeRouteImport } from './routes/admin/knowledge'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoAshaRouteImport } from './routes/demo/asha'
import { Route as DemoIntegrationHealthRouteImport } from './routes/demo/integration-health'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents/$documentId'
import { Route as EligibilitySchemeCodeRouteImport } from './routes/eligibility/$schemeCode'
import { Route as ReadinessIndexRouteImport } from './routes/readiness/index'
import { Route as ReadinessSchemeCodeRouteImport } from './routes/readiness/$schemeCode'
import { Route as SchemesIndexRouteImport } from './routes/schemes/index'
import { Route as SchemesSchemeCodeRouteImport } from './routes/schemes/$schemeCode'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApplicationsApplicationIdIndexRouteImport } from './routes/applications/$applicationId/index'
import { Route as ApplicationsApplicationIdResolveRouteImport } from './routes/applications/$applicationId/resolve'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationHealthRoute = IntegrationHealthRouteImport.update({
  id: '/integration-health',
  path: '/integration-health',
  getParentRoute: () => rootRouteImport,
} as any)
const JagoRoute = JagoRouteImport.update({
  id: '/jago',
  path: '/jago',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualReviewRoute = ManualReviewRouteImport.update({
  id: '/manual-review',
  path: '/manual-review',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyConsentRoute = PrivacyConsentRouteImport.update({
  id: '/privacy-consent',
  path: '/privacy-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedGuidanceRoute = SavedGuidanceRouteImport.update({
  id: '/saved-guidance',
  path: '/saved-guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOnceRoute = VerifyOnceRouteImport.update({
  id: '/verify-once',
  path: '/verify-once',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeleteRoute = AccountDeleteRouteImport.update({
  id: '/account/delete',
  path: '/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/admin/knowledge',
  path: '/admin/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAshaRoute = DemoAshaRouteImport.update({
  id: '/demo/asha',
  path: '/demo/asha',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIntegrationHealthRoute = DemoIntegrationHealthRouteImport.update({
  id: '/demo/integration-health',
  path: '/demo/integration-health',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilitySchemeCodeRoute = EligibilitySchemeCodeRouteImport.update({
  id: '/eligibility/$schemeCode',
  path: '/eligibility/$schemeCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessIndexRoute = ReadinessIndexRouteImport.update({
  id: '/readiness/',
  path: '/readiness/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessSchemeCodeRoute = ReadinessSchemeCodeRouteImport.update({
  id: '/readiness/$schemeCode',
  path: '/readiness/$schemeCode',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIndexRoute = SchemesIndexRouteImport.update({
  id: '/schemes/',
  path: '/schemes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesSchemeCodeRoute = SchemesSchemeCodeRouteImport.update({
  id: '/schemes/$schemeCode',
  path: '/schemes/$schemeCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdIndexRoute =
  ApplicationsApplicationIdIndexRouteImport.update({
    id: '/applications/$applicationId/',
    path: '/applications/$applicationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdResolveRoute =
  ApplicationsApplicationIdResolveRouteImport.update({
    id: '/applications/$applicationId/resolve',
    path: '/applications/$applicationId/resolve',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checklist': typeof ChecklistRoute
  '/connect': typeof ConnectRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/guide': typeof GuideRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integration-health': typeof IntegrationHealthRoute
  '/jago': typeof JagoRoute
  '/login': typeof LoginRoute
  '/manual-review': typeof ManualReviewRoute
  '/notifications': typeof NotificationsRoute
  '/officer': typeof OfficerRoute
  '/onboarding': typeof OnboardingRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-consent': typeof PrivacyConsentRoute
  '/profile': typeof ProfileRoute
  '/saved-guidance': typeof SavedGuidanceRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-once': typeof VerifyOnceRoute
  '/account/delete': typeof AccountDeleteRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/demo/asha': typeof DemoAshaRoute
  '/demo/integration-health': typeof DemoIntegrationHealthRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/eligibility/$schemeCode': typeof EligibilitySchemeCodeRoute
  '/readiness/$schemeCode': typeof ReadinessSchemeCodeRoute
  '/schemes/$schemeCode': typeof SchemesSchemeCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/readiness/': typeof ReadinessIndexRoute
  '/schemes/': typeof SchemesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/applications/$applicationId/resolve': typeof ApplicationsApplicationIdResolveRoute
  '/applications/$applicationId/': typeof ApplicationsApplicationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checklist': typeof ChecklistRoute
  '/connect': typeof ConnectRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/guide': typeof GuideRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integration-health': typeof IntegrationHealthRoute
  '/jago': typeof JagoRoute
  '/login': typeof LoginRoute
  '/manual-review': typeof ManualReviewRoute
  '/notifications': typeof NotificationsRoute
  '/officer': typeof OfficerRoute
  '/onboarding': typeof OnboardingRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-consent': typeof PrivacyConsentRoute
  '/profile': typeof ProfileRoute
  '/saved-guidance': typeof SavedGuidanceRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-once': typeof VerifyOnceRoute
  '/account/delete': typeof AccountDeleteRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/demo/asha': typeof DemoAshaRoute
  '/demo/integration-health': typeof DemoIntegrationHealthRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/eligibility/$schemeCode': typeof EligibilitySchemeCodeRoute
  '/readiness/$schemeCode': typeof ReadinessSchemeCodeRoute
  '/schemes/$schemeCode': typeof SchemesSchemeCodeRoute
  '/admin': typeof AdminIndexRoute
  '/applications': typeof ApplicationsIndexRoute
  '/demo': typeof DemoIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/readiness': typeof ReadinessIndexRoute
  '/schemes': typeof SchemesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/applications/$applicationId/resolve': typeof ApplicationsApplicationIdResolveRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checklist': typeof ChecklistRoute
  '/connect': typeof ConnectRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/guide': typeof GuideRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integration-health': typeof IntegrationHealthRoute
  '/jago': typeof JagoRoute
  '/login': typeof LoginRoute
  '/manual-review': typeof ManualReviewRoute
  '/notifications': typeof NotificationsRoute
  '/officer': typeof OfficerRoute
  '/onboarding': typeof OnboardingRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-consent': typeof PrivacyConsentRoute
  '/profile': typeof ProfileRoute
  '/saved-guidance': typeof SavedGuidanceRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-once': typeof VerifyOnceRoute
  '/account/delete': typeof AccountDeleteRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/demo/asha': typeof DemoAshaRoute
  '/demo/integration-health': typeof DemoIntegrationHealthRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/eligibility/$schemeCode': typeof EligibilitySchemeCodeRoute
  '/readiness/$schemeCode': typeof ReadinessSchemeCodeRoute
  '/schemes/$schemeCode': typeof SchemesSchemeCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/readiness/': typeof ReadinessIndexRoute
  '/schemes/': typeof SchemesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/applications/$applicationId/resolve': typeof ApplicationsApplicationIdResolveRoute
  '/applications/$applicationId/': typeof ApplicationsApplicationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checklist'
    | '/connect'
    | '/consent'
    | '/dashboard'
    | '/feedback'
    | '/guide'
    | '/how-it-works'
    | '/integration-health'
    | '/jago'
    | '/login'
    | '/manual-review'
    | '/notifications'
    | '/officer'
    | '/onboarding'
    | '/payments'
    | '/privacy'
    | '/privacy-consent'
    | '/profile'
    | '/saved-guidance'
    | '/settings'
    | '/signup'
    | '/support'
    | '/terms'
    | '/verify-once'
    | '/account/delete'
    | '/admin/audit'
    | '/admin/feedback'
    | '/admin/knowledge'
    | '/demo/asha'
    | '/demo/integration-health'
    | '/documents/$documentId'
    | '/eligibility/$schemeCode'
    | '/readiness/$schemeCode'
    | '/schemes/$schemeCode'
    | '/admin/'
    | '/applications/'
    | '/demo/'
    | '/documents/'
    | '/readiness/'
    | '/schemes/'
    | '/api/auth/$'
    | '/applications/$applicationId/resolve'
    | '/applications/$applicationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checklist'
    | '/connect'
    | '/consent'
    | '/dashboard'
    | '/feedback'
    | '/guide'
    | '/how-it-works'
    | '/integration-health'
    | '/jago'
    | '/login'
    | '/manual-review'
    | '/notifications'
    | '/officer'
    | '/onboarding'
    | '/payments'
    | '/privacy'
    | '/privacy-consent'
    | '/profile'
    | '/saved-guidance'
    | '/settings'
    | '/signup'
    | '/support'
    | '/terms'
    | '/verify-once'
    | '/account/delete'
    | '/admin/audit'
    | '/admin/feedback'
    | '/admin/knowledge'
    | '/demo/asha'
    | '/demo/integration-health'
    | '/documents/$documentId'
    | '/eligibility/$schemeCode'
    | '/readiness/$schemeCode'
    | '/schemes/$schemeCode'
    | '/admin'
    | '/applications'
    | '/demo'
    | '/documents'
    | '/readiness'
    | '/schemes'
    | '/api/auth/$'
    | '/applications/$applicationId/resolve'
    | '/applications/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/checklist'
    | '/connect'
    | '/consent'
    | '/dashboard'
    | '/feedback'
    | '/guide'
    | '/how-it-works'
    | '/integration-health'
    | '/jago'
    | '/login'
    | '/manual-review'
    | '/notifications'
    | '/officer'
    | '/onboarding'
    | '/payments'
    | '/privacy'
    | '/privacy-consent'
    | '/profile'
    | '/saved-guidance'
    | '/settings'
    | '/signup'
    | '/support'
    | '/terms'
    | '/verify-once'
    | '/account/delete'
    | '/admin/audit'
    | '/admin/feedback'
    | '/admin/knowledge'
    | '/demo/asha'
    | '/demo/integration-health'
    | '/documents/$documentId'
    | '/eligibility/$schemeCode'
    | '/readiness/$schemeCode'
    | '/schemes/$schemeCode'
    | '/admin/'
    | '/applications/'
    | '/demo/'
    | '/documents/'
    | '/readiness/'
    | '/schemes/'
    | '/api/auth/$'
    | '/applications/$applicationId/resolve'
    | '/applications/$applicationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChecklistRoute: typeof ChecklistRoute
  ConnectRoute: typeof ConnectRoute
  ConsentRoute: typeof ConsentRoute
  DashboardRoute: typeof DashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  GuideRoute: typeof GuideRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IntegrationHealthRoute: typeof IntegrationHealthRoute
  JagoRoute: typeof JagoRoute
  LoginRoute: typeof LoginRoute
  ManualReviewRoute: typeof ManualReviewRoute
  NotificationsRoute: typeof NotificationsRoute
  OfficerRoute: typeof OfficerRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentsRoute: typeof PaymentsRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyConsentRoute: typeof PrivacyConsentRoute
  ProfileRoute: typeof ProfileRoute
  SavedGuidanceRoute: typeof SavedGuidanceRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VerifyOnceRoute: typeof VerifyOnceRoute
  AccountDeleteRoute: typeof AccountDeleteRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  DemoAshaRoute: typeof DemoAshaRoute
  DemoIntegrationHealthRoute: typeof DemoIntegrationHealthRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  EligibilitySchemeCodeRoute: typeof EligibilitySchemeCodeRoute
  ReadinessSchemeCodeRoute: typeof ReadinessSchemeCodeRoute
  SchemesSchemeCodeRoute: typeof SchemesSchemeCodeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  ReadinessIndexRoute: typeof ReadinessIndexRoute
  SchemesIndexRoute: typeof SchemesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApplicationsApplicationIdResolveRoute: typeof ApplicationsApplicationIdResolveRoute
  ApplicationsApplicationIdIndexRoute: typeof ApplicationsApplicationIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration-health': {
      id: '/integration-health'
      path: '/integration-health'
      fullPath: '/integration-health'
      preLoaderRoute: typeof IntegrationHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jago': {
      id: '/jago'
      path: '/jago'
      fullPath: '/jago'
      preLoaderRoute: typeof JagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-review': {
      id: '/manual-review'
      path: '/manual-review'
      fullPath: '/manual-review'
      preLoaderRoute: typeof ManualReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-consent': {
      id: '/privacy-consent'
      path: '/privacy-consent'
      fullPath: '/privacy-consent'
      preLoaderRoute: typeof PrivacyConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-guidance': {
      id: '/saved-guidance'
      path: '/saved-guidance'
      fullPath: '/saved-guidance'
      preLoaderRoute: typeof SavedGuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-once': {
      id: '/verify-once'
      path: '/verify-once'
      fullPath: '/verify-once'
      preLoaderRoute: typeof VerifyOnceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/delete': {
      id: '/account/delete'
      path: '/account/delete'
      fullPath: '/account/delete'
      preLoaderRoute: typeof AccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/admin/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/asha': {
      id: '/demo/asha'
      path: '/demo/asha'
      fullPath: '/demo/asha'
      preLoaderRoute: typeof DemoAshaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/integration-health': {
      id: '/demo/integration-health'
      path: '/demo/integration-health'
      fullPath: '/demo/integration-health'
      preLoaderRoute: typeof DemoIntegrationHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility/$schemeCode': {
      id: '/eligibility/$schemeCode'
      path: '/eligibility/$schemeCode'
      fullPath: '/eligibility/$schemeCode'
      preLoaderRoute: typeof EligibilitySchemeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/': {
      id: '/readiness/'
      path: '/readiness'
      fullPath: '/readiness/'
      preLoaderRoute: typeof ReadinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/$schemeCode': {
      id: '/readiness/$schemeCode'
      path: '/readiness/$schemeCode'
      fullPath: '/readiness/$schemeCode'
      preLoaderRoute: typeof ReadinessSchemeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/': {
      id: '/schemes/'
      path: '/schemes'
      fullPath: '/schemes/'
      preLoaderRoute: typeof SchemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/$schemeCode': {
      id: '/schemes/$schemeCode'
      path: '/schemes/$schemeCode'
      fullPath: '/schemes/$schemeCode'
      preLoaderRoute: typeof SchemesSchemeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/': {
      id: '/applications/$applicationId/'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId/'
      preLoaderRoute: typeof ApplicationsApplicationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/resolve': {
      id: '/applications/$applicationId/resolve'
      path: '/applications/$applicationId/resolve'
      fullPath: '/applications/$applicationId/resolve'
      preLoaderRoute: typeof ApplicationsApplicationIdResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChecklistRoute: ChecklistRoute,
  ConnectRoute: ConnectRoute,
  ConsentRoute: ConsentRoute,
  DashboardRoute: DashboardRoute,
  FeedbackRoute: FeedbackRoute,
  GuideRoute: GuideRoute,
  HowItWorksRoute: HowItWorksRoute,
  IntegrationHealthRoute: IntegrationHealthRoute,
  JagoRoute: JagoRoute,
  LoginRoute: LoginRoute,
  ManualReviewRoute: ManualReviewRoute,
  NotificationsRoute: NotificationsRoute,
  OfficerRoute: OfficerRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentsRoute: PaymentsRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyConsentRoute: PrivacyConsentRoute,
  ProfileRoute: ProfileRoute,
  SavedGuidanceRoute: SavedGuidanceRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VerifyOnceRoute: VerifyOnceRoute,
  AccountDeleteRoute: AccountDeleteRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  DemoAshaRoute: DemoAshaRoute,
  DemoIntegrationHealthRoute: DemoIntegrationHealthRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  EligibilitySchemeCodeRoute: EligibilitySchemeCodeRoute,
  ReadinessSchemeCodeRoute: ReadinessSchemeCodeRoute,
  SchemesSchemeCodeRoute: SchemesSchemeCodeRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  DemoIndexRoute: DemoIndexRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  ReadinessIndexRoute: ReadinessIndexRoute,
  SchemesIndexRoute: SchemesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApplicationsApplicationIdResolveRoute: ApplicationsApplicationIdResolveRoute,
  ApplicationsApplicationIdIndexRoute: ApplicationsApplicationIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
